# Generated by Django 6.0.4 on 2026-04-26 15:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField(unique=True)),
                ('oracle_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=100)),
                ('cmc', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('type_line', models.CharField(max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('loyalty', models.CharField(blank=True, max_length=10)),
                ('defense', models.CharField(blank=True, max_length=10)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list)),
                ('color_identity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list)),
                ('set_code', models.CharField(max_length=10)),
                ('set_name', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic')], max_length=20)),
                ('collector_number', models.CharField(max_length=10)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('legal_standard', models.BooleanField(default=False)),
                ('legal_pioneer', models.BooleanField(default=False)),
                ('legal_modern', models.BooleanField(default=False)),
                ('legal_legacy', models.BooleanField(default=False)),
                ('legal_vintage', models.BooleanField(default=False)),
                ('legal_commander', models.BooleanField(default=False)),
                ('legal_pauper', models.BooleanField(default=False)),
                ('image_uri', models.URLField(blank=True)),
                ('layout', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['oracle_id'], name='cards_card_oracle__d775c8_idx'), models.Index(fields=['set_code'], name='cards_card_set_cod_d6cc57_idx')],
                'unique_together': {('scryfall_id', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=100)),
                ('type_line', models.CharField(blank=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('loyalty', models.CharField(blank=True, max_length=10)),
                ('image_uri', models.URLField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='cards.card')),
            ],
            options={
                'ordering': ['face_index'],
                'unique_together': {('card', 'face_index')},
            },
        ),
    ]
