# docker-compose.production.yml

volumes:
  pgdata:

services:
  postgres:
    image: postgres:16
#    environment:
#      POSTGRES_DB: mtgo
#      POSTGRES_USER: mtgo
#      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  django:
    image: rtem4i4ik/mtg_online_table_django
    env_file:
      - .env
    depends_on:
      - postgres

  go-service:
    image: gg/mtg_online_table_golang
    volumes:
      - ./go-service:/app
    env_file:
      - .env
#    environment:
#      REDIS_URL: redis://redis:6379
#      DJANGO_API_URL: http://django:8000
    depends_on: [ redis, django ]

  frontend:
    image: gg/mtg_online_table_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on: [ django, go-service, frontend ]
