# docker-compose.production.yml

volumes:
  pgdata:
  static:

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    image: rtem4i4ik/mtg_django
    env_file:
      - .env
    volumes:
      - static:/backend_static
    depends_on:
      - postgres

  go-service:
    image: rtem4i4ik/mtg_golang
    volumes:
      - ./go-service:/app
    env_file:
      - .env
    depends_on: django

  frontend:
    image: rtem4i4ik/mtg_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  gateway:
    image: rtem4i4ik/mtg_gateway
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
    depends_on:
      - django
      - go-service
      - frontend