# docker-compose.yml

volumes:
  pgdata:
  static:

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./django_service/
    env_file:
      - .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  go-service:
    build: ./go-service
    env_file:
      - .env
    depends_on:
      - django

  frontend:
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  gateway:
    build: ./nginx
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - django
      - go-service
      - frontend

