# Generated by Django 6.0.4 on 2026-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('deck_min_size', models.IntegerField(default=60)),
                ('deck_max_size', models.IntegerField(blank=True, null=True)),
                ('sideboard_size', models.IntegerField(default=15)),
            ],
        ),
    ]
