events {}

http {
    upstream django   { server django:8000; }
    upstream go_ws    { server go-service:8080; }
    upstream frontend { server frontend:5173; }

    server {
        listen 80;

        location /api/   { proxy_pass http://django; }
        location /admin/ { proxy_pass http://django; }

        location /game-ws/ {
            proxy_pass http://go_ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / { proxy_pass http://frontend; }
    }
}
