# Generated by Django 6.0.4 on 2026-09-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('formats', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_decks', to='formats.format'),
        ),
    ]
